[tool.poetry]
name = "repl_python3_Reddit-Rickroll-Bot"
version = "0.1.0"
description = ""
authors = ["EdZ123 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
praw = "^7.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
